/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejercicio1;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author danny
 */
public class FrmEjercicio1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmEjercicio1.class.getName());

    fondopanel fondo = new fondopanel();
    operaciones operar = new operaciones();
    
    /**
     * Creates new form FrmEjercicio1
     */
    public FrmEjercicio1() {
        initComponents();
        txtResultado.setEnabled(false);
        this.getContentPane().setBackground(Color.darkGray);//Cambiar color de fondo
        this.setLocationRelativeTo(null);//Centrar Formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new fondopanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnumero1 = new javax.swing.JTextField();
        txtnumero2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnsumar = new javax.swing.JButton();
        btnrestar = new javax.swing.JButton();
        btnproducto = new javax.swing.JButton();
        btndivision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ejemplo 1");

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero 1");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero 2");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultado");

        btnsumar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnsumar.setText("+");
        btnsumar.addActionListener(this::btnsumarActionPerformed);

        btnrestar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnrestar.setText("-");
        btnrestar.addActionListener(this::btnrestarActionPerformed);

        btnproducto.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnproducto.setText("*");
        btnproducto.addActionListener(this::btnproductoActionPerformed);

        btndivision.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btndivision.setText("/");
        btndivision.addActionListener(this::btndivisionActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnumero1)
                            .addComponent(txtnumero2)
                            .addComponent(txtResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnsumar)
                            .addComponent(btnrestar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnproducto)
                            .addComponent(btndivision))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsumar)
                            .addComponent(btnproducto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnrestar)
                            .addComponent(btndivision))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
        
        if(txtnumero1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            
            txtnumero1.requestFocus();
        }
        
        if(txtnumero2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            
            txtnumero2.requestFocus();
        }
        
        double num1 = Double.parseDouble(txtnumero1.getText());
        
        double num2 = Double.parseDouble(txtnumero2.getText());
        
        operar.sumar(num1, num2);
        
        txtResultado.setText(String.valueOf(operar.resultado));
        
        txtnumero1.setText("");
        txtnumero2.setText("");
        
        
    }//GEN-LAST:event_btnsumarActionPerformed

    private void btnrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestarActionPerformed
        
        if(txtnumero1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        }
        
        if(txtnumero2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        }
        
        double num1 = Double.parseDouble(txtnumero1.getText());
        
        double num2 = Double.parseDouble(txtnumero2.getText());
        
        operar.restar(num1, num2);
        
        txtResultado.setText(String.valueOf(operar.resultado));
        
        txtnumero1.setText("");
        txtnumero2.setText("");
    }//GEN-LAST:event_btnrestarActionPerformed

    private void btnproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproductoActionPerformed
        
        if(txtnumero1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        }
        
        if(txtnumero2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        }
        
        double num1 = Double.parseDouble(txtnumero1.getText());
        
        double num2 = Double.parseDouble(txtnumero2.getText());
        
        operar.multiplicar(num1, num2);
        
        txtResultado.setText(String.valueOf(operar.resultado));
        
        txtnumero1.setText("");
        txtnumero2.setText("");
    }//GEN-LAST:event_btnproductoActionPerformed

    private void btndivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivisionActionPerformed
        
        if(txtnumero1.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        }
        
        if(txtnumero2.getText().trim().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Ingrese un numero", "Campo es requerido", JOptionPane.WARNING_MESSAGE);
            txtnumero1.requestFocus();
        } 
        
        double num1 = Double.parseDouble(txtnumero1.getText());
        
        double num2 = Double.parseDouble(txtnumero2.getText());
        
        operar.dividir(num1, num2);
        
        txtResultado.setText(String.valueOf(operar.resultado));
        
        txtnumero1.setText("");
        txtnumero2.setText("");
    }//GEN-LAST:event_btndivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmEjercicio1().setVisible(true));
    }
    
    //Agregar fondo al JPanel
    class fondopanel extends JPanel{
        
        private Image imagen;
        
        @Override
        
        protected void paintComponent(Graphics g){
            super.paintComponent(g);
            imagen = new ImageIcon(
                    
                    
                getClass().getResource("/imagenes/fondo.jpeg")
            ).getImage();
            
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndivision;
    private javax.swing.JButton btnproducto;
    private javax.swing.JButton btnrestar;
    private javax.swing.JButton btnsumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtnumero1;
    private javax.swing.JTextField txtnumero2;
    // End of variables declaration//GEN-END:variables
}
